DROP TABLE IF EXISTS customers;
CREATE TABLE customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    image_path VARCHAR(500) NULL,
    Description VARCHAR(255),
    Age INT,
    Course VARCHAR(255),
    Password VARCHAR(255),
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);